### ISSUE TITLE
Additional questions

### ISSUE THREAD

**Issue by eolexe** [seesawlabs/raphael-assignment#1]
Assignment is done good. If you don’t mind I have several additional question:
1. How would you implement authentication functionality. Describe architecture, and chosen approaches/technologies
2. goose requires it’s own config file for using migrations, which makes config been duplicated in to places. How would you overcome/alternatives this issue?
3. You need to check incoming parameter across allowed values like: red, blue, green, yellow, black, purple ...  , what would be the most optimal solution?
4. You are integrating with 3-rd party API. You need to make about 10 requests to different API endpoints for single action, which slowdowns your UI dramatically. Describe strategies to improve performance, any go specific ways to speed up the process?

**Comment by raphaeljlps** [comment]
Hello Max, 
Of course I don't mind, I will do my best to try answer you questions
That being said let's begin with your first question:

>  How would you implement authentication functionality. Describe architecture, and chosen approaches/technologies

Well, I would implement a token based authentication in a middleware and after validating the token, I would put the user in the context (considering the tech used for this project, and trying to do something simple). 

```go
/// Pseudo Go
func (c *Context) AuthMiddlware(rw web.ResponseWriter, req *web.Request
                                                     next web.NextMiddlewareFunc) {
   token, err := getToken(req.Header)
   //verify error
   user, err := getUserWithToken(token)
   if user == nil || err != nil {
      //return forbidden
      return
   }

   c.User = user
   next(rw, r)
}
```

I would have create a table like thins
```go
type APIKey struct {
	Id        int
	Hash      string `sql:"not null;unique"`
	UserId    int    `sql:"not null"`
	CreatedAt time.Time
	ExpireAt  time.Time `sql:"not null"`
}

//BeforeCreate validates if exist only one AccessKey
//with the same hash before creating the AccessKey.
func (ak *AccessKey) BeforeCreate(tx *gorm.DB) (err error) {
	for {
		hash, err := randomHex(64)
		if err != nil {
			break
		}

		key := AccessKey{}
		tx.Where("hash = ?", hash).First(&key)
		if key.ID == 0 {
			ak.Hash = hash
			break
		}

	}

	hours := 30 * 24 //30 days
	thirtyDays := time.Duration(hours) * time.Hour
	now := time.Now()
	expire := now.Add(thirtyDays)

	//config to expire in 30 days
	ak.ExpireAt = expire

	return
}

func randomHex(n int) (string, error) {
	bytes := make([]byte, n)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

```
 


So, the Client Application would send a POST request to /login through a https conn and receive a token for the subsequent requests. 

Of course, it all depends of the requirements, so instead I could use other techs, like [JWT](https://github.com/dgrijalva/jwt-go) or [OAuth](https://github.com/golang/oauth2).

There is an interesting approach in [this link](https://neosmart.net/blog/2015/using-hmac-signatures-to-avoid-database-writes/) too.

**Comment by raphaeljlps** [comment]
> goose requires it’s own config file for using migrations, which makes config been duplicated in to places. How would you overcome/alternatives this issue?

Well, as I have a shallow knowledge of goose, I will assume that I MUST have this config file  somewhere and can't pass the required fields as params or add them in another config file and give it to goose.

I would build some tool to automate my workflow, like a command line app (or a script) to handle both config files, where I could specify the paths and forget about the dbconfig.yml.
 
configtool --maincfg=config.json --goose=db/

so the config tool would read the configs from config.json and write the appropriate dbconfig.yml for goose.

**Comment by raphaeljlps** [comment]
> You need to check incoming parameter across allowed values like: red, blue, green, yellow, black, purple ... , what would be the most optimal solution?

I would build a hash table with the allowed values and search the incoming parameter in the hash table,
as the average search time of a hash tables is O(1) and in the worse case is O(n).

**Comment by raphaeljlps** [comment]
> You are integrating with 3-rd party API. You need to make about 10 requests to different API endpoints for single action, which slowdowns your UI dramatically. Describe strategies to improve performance, any go specific ways to speed up the process?

(Go specific way)
I would separate each API request in its own goroutine *(green thread)* and coordinate between them through go  channels.

**Comment by eolexe** [comment]
Hi @raphaeljlps thank you for your answers, they are very informative and full.
